// content/_data/pokemonFaveShinyList.js

export const FAVE_GROUP_LABELS = {
  "pink-faves": "Pink Faves",
  "cute-faves": "Cute Faves",
  "goth-witchy-faves": "Goth / Witchy Faves",
  "frog-faves": "Frog Faves",
};

export default [
  // 🌸 Pink Faves
  {
    species: "Hypno",
    dexNo: "97",
    group: "pink-faves",
    emoji: "🌙",
    vibe: "dreamy pink menace",
  },
  {
    species: "Dragonair",
    dexNo: "148",
    group: "pink-faves",
    emoji: "🌸",
    vibe: "pastel serpent angel",
  },
  {
    species: "Aerodactyl",
    dexNo: "142",
    group: "pink-faves",
    emoji: "🦴",
    vibe: "pink fossil icon",
  },
  {
    species: "Heracross",
    dexNo: "214",
    group: "pink-faves",
    emoji: "🌸",
    vibe: "pink beetle legend",
  },
  {
    species: "Mareep",
    dexNo: "179",
    group: "pink-faves",
    emoji: "🐑",
    vibe: "cotton candy sheep",
  },
  {
    species: "Flaaffy",
    dexNo: "180",
    group: "pink-faves",
    emoji: "🐑",
    vibe: "pink sheep girl",
  },
  {
    species: "Ampharos",
    dexNo: "181",
    group: "pink-faves",
    emoji: "⚡",
    vibe: "rosy electric lighthouse",
  },
  {
    species: "Mareanie",
    dexNo: "747",
    group: "pink-faves",
    emoji: "🪸",
    vibe: "spiky pastel tidepool baby",
  },
  {
    species: "Toxapex",
    dexNo: "748",
    group: "pink-faves",
    emoji: "🪸",
    vibe: "toxic sea princess",
  },
  {
    species: "Lechonk",
    dexNo: "915",
    group: "pink-faves",
    emoji: "🐷",
    vibe: "pink little hog",
  },
  {
    species: "Flamigo",
    dexNo: "973",
    group: "pink-faves",
    emoji: "🦩",
    vibe: "camp pink bird",
  },
  {
    species: "Scream Tail",
    dexNo: "985",
    group: "pink-faves",
    emoji: "🌙",
    vibe: "pastel cryptid Jigglypuff",
  },

  // 🎀 Cute Faves
  {
    species: "Clefairy",
    dexNo: "35",
    group: "cute-faves",
    emoji: "🎀",
    vibe: "moon fairy baby",
  },
  {
    species: "Jigglypuff",
    dexNo: "39",
    group: "cute-faves",
    emoji: "🎤",
    vibe: "pink karaoke menace",
  },
  {
    species: "Slowpoke",
    dexNo: "79",
    group: "cute-faves",
    emoji: "💤",
    vibe: "perfect sleepy friend",
  },
  {
    species: "Lapras",
    dexNo: "131",
    group: "cute-faves",
    emoji: "💜",
    vibe: "soft lavender queen",
  },
  {
    species: "Vaporeon",
    dexNo: "134",
    group: "cute-faves",
    emoji: "💧",
    vibe: "purple mermaid cat",
  },
  {
    species: "Dratini",
    dexNo: "147",
    group: "cute-faves",
    emoji: "🌸",
    vibe: "tiny pink noodle",
  },
  {
    species: "Furret",
    dexNo: "162",
    group: "cute-faves",
    emoji: "🎀",
    vibe: "long pink baby",
  },
  {
    species: "Wooper",
    dexNo: "194",
    group: "cute-faves",
    emoji: "🌸",
    vibe: "perfect silly pink friend",
  },
  {
    species: "Dunsparce",
    dexNo: "206",
    group: "cute-faves",
    emoji: "🌸",
    vibe: "silly pink angel worm",
  },
  {
    species: "Buneary",
    dexNo: "427",
    group: "cute-faves",
    emoji: "🐰",
    vibe: "soft bunny sparkle",
  },
  {
    species: "Lopunny",
    dexNo: "428",
    group: "cute-faves",
    emoji: "🐰",
    vibe: "pastel bunny glam",
  },
  {
    species: "Goomy",
    dexNo: "704",
    group: "cute-faves",
    emoji: "🐌",
    vibe: "squishy lavender blob",
  },
  {
    species: "Goodra",
    dexNo: "706",
    group: "cute-faves",
    emoji: "🐉",
    vibe: "soft dragon friend",
  },
  {
    species: "Hisuian Goodra",
    dexNo: "706",
    form: "Hisuian",
    group: "cute-faves",
    emoji: "🐉",
    vibe: "clingy shell dragon",
  },
  {
    species: "Cutiefly",
    dexNo: "742",
    group: "cute-faves",
    emoji: "🧚",
    vibe: "tiny fairy bug",
  },
  {
    species: "Ribombee",
    dexNo: "743",
    group: "cute-faves",
    emoji: "🧚",
    vibe: "pastel pollen fairy",
  },
  {
    species: "Pawmi",
    dexNo: "921",
    group: "cute-faves",
    emoji: "⚡",
    vibe: "tiny strawberry mouse",
  },
  {
    species: "Pawmot",
    dexNo: "923",
    group: "cute-faves",
    emoji: "⚡",
    vibe: "strawberry electric buddy",
  },

  // 🖤 Goth / Witchy Faves
  {
    species: "Gengar",
    dexNo: "94",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "classic ghost gremlin",
  },
  {
    species: "Crobat",
    dexNo: "169",
    group: "goth-witchy-faves",
    emoji: "🦇",
    vibe: "pink cave goth",
  },
  {
    species: "Misdreavus",
    dexNo: "200",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "ghost girl energy",
  },
  {
    species: "Mismagius",
    dexNo: "429",
    group: "goth-witchy-faves",
    emoji: "🧙‍♀️",
    vibe: "literal witch ghost",
  },
  {
    species: "Murkrow",
    dexNo: "198",
    group: "goth-witchy-faves",
    emoji: "🐦‍⬛",
    vibe: "tiny witch crow",
  },
  {
    species: "Honchkrow",
    dexNo: "430",
    group: "goth-witchy-faves",
    emoji: "🐦‍⬛",
    vibe: "mob boss witch crow",
  },
  {
    species: "Sneasel",
    dexNo: "215",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "pink goth cat",
  },
  {
    species: "Weavile",
    dexNo: "461",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "pink dark-type diva",
  },
  {
    species: "Hisuian Sneasel",
    dexNo: "215",
    form: "Hisuian",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "poison pink menace",
  },
  {
    species: "Sneasler",
    dexNo: "903",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "tall poison goth cat",
  },
  {
    species: "Banette",
    dexNo: "354",
    group: "goth-witchy-faves",
    emoji: "🧵",
    vibe: "haunted doll energy",
  },
  {
    species: "Gothita",
    dexNo: "574",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "baby gothic doll",
  },
  {
    species: "Gothorita",
    dexNo: "575",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "stargazing goth girl",
  },
  {
    species: "Gothitelle",
    dexNo: "576",
    group: "goth-witchy-faves",
    emoji: "🖤",
    vibe: "cosmic gothic oracle",
  },
  {
    species: "Salandit",
    dexNo: "757",
    group: "goth-witchy-faves",
    emoji: "🦎",
    vibe: "toxic little goth lizard",
  },
  {
    species: "Salazzle",
    dexNo: "758",
    group: "goth-witchy-faves",
    emoji: "🦎",
    vibe: "poison glam villain",
  },
  {
    species: "Mimikyu",
    dexNo: "778",
    group: "goth-witchy-faves",
    emoji: "👻",
    vibe: "lonely spooky plushie",
  },
  {
    species: "Toxel",
    dexNo: "848",
    group: "goth-witchy-faves",
    emoji: "🎸",
    vibe: "tiny punk gremlin",
  },
  {
    species: "Toxtricity",
    dexNo: "849",
    group: "goth-witchy-faves",
    emoji: "🎸",
    vibe: "pink electric punk",
  },
  {
    species: "Hatenna",
    dexNo: "856",
    group: "goth-witchy-faves",
    emoji: "🔮",
    vibe: "pastel witch baby",
  },
  {
    species: "Hattrem",
    dexNo: "857",
    group: "goth-witchy-faves",
    emoji: "🔮",
    vibe: "soft witch rage",
  },
  {
    species: "Hatterene",
    dexNo: "858",
    group: "goth-witchy-faves",
    emoji: "🔮",
    vibe: "pastel witch queen",
  },

  // 🐸 Frog Faves
  {
    species: "Bulbasaur",
    dexNo: "1",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "starter frog-adjacent baby",
  },
  {
    species: "Venusaur",
    dexNo: "3",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "big flower frog tank",
  },
  {
    species: "Poliwag",
    dexNo: "60",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "tiny tadpole swirl",
  },
  {
    species: "Poliwhirl",
    dexNo: "61",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "round frog friend",
  },
  {
    species: "Politoed",
    dexNo: "186",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "cheerful frog king",
  },
  {
    species: "Croagunk",
    dexNo: "453",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "poison frog gremlin",
  },
  {
    species: "Toxicroak",
    dexNo: "454",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "gothy poison frog",
  },
  {
    species: "Tympole",
    dexNo: "535",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "tiny sound tadpole",
  },
  {
    species: "Palpitoad",
    dexNo: "536",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "bumpy little pond guy",
  },
  {
    species: "Seismitoad",
    dexNo: "537",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "big swamp boss",
  },
  {
    species: "Froakie",
    dexNo: "656",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "blue ninja frog baby",
  },
  {
    species: "Frogadier",
    dexNo: "657",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "sleek frog ninja",
  },
  {
    species: "Greninja",
    dexNo: "658",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "black shiny ninja icon",
  },
  {
    species: "Tadbulb",
    dexNo: "938",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "tiny electric tadpole light",
  },
  {
    species: "Bellibolt",
    dexNo: "939",
    group: "frog-faves",
    emoji: "🐸",
    vibe: "round electric frog mascot",
  },
];