// content/_data/pokemonPinkQuestList.js

export const PINK_QUEST_LABELS = {
  "pink-switch": "Switch Pink Quest",
  "pink-switch-optional": "Switch Pink Quest — Optional",
  "pink-frlg": "FRLG Side Hunts",
};

export const PINK_SWITCH_SPECIES = [
  // Gen 1
  "Butterfree",
  "Slowpoke",
  "Drowzee",
  "Hypno",
  "Magmar",
  "Aerodactyl",
  "Porygon",
  "Dratini",
  "Dragonair",

  // Gen 2
  "Spinarak",
  "Ariados",
  "Crobat",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Ambipom",
  "Wooper",
  "Paldean Wooper",
  "Politoed",
  "Wynaut",
  "Wobbuffet",
  "Dunsparce",
  "Dudunsparce",
  "Sneasel",
  "Weavile",
  "Heracross",
  "Furret",

  // Gen 3
  "Whismur",
  "Meditite",
  "Medicham",
  "Spoink",
  "Corphish",
  "Lileep",
  "Cradily",
  "Castform",

  // Gen 4
  "West Sea Shellos",
  "West Sea Gastrodon",
  "Buneary",
  "Lopunny",
  "Magby",
  "Magmortar",
  "Porygon2",
  "Porygon-Z",
  "Palkia",

  // Gen 5
  "Audino",
  "Unovan Darumaka",
  "Minccino",
  "Cinccino",
  "Ducklett",
  "Swanna",
  "Alomomola",
  "Mienfoo",
  "Mienshao",
  "Vullaby",
  "Mandibuzz",
  "Virizion",

  // Gen 6
  "Furfrou",
  "Furfrou Heart Trim",
  "Spritzee",
  "Aromatisse",
  "Binacle",
  "Barbaracle",
  "Goomy",
  "Sliggoo",
  "Goodra",
  "Hisuian Sliggoo",
  "Hisuian Goodra",

  // Gen 7
  "Yungoos",
  "Gumshoos",
  "Oricorio Baile",
  "Oricorio Pa'u",
  "Cutiefly",
  "Ribombee",
  "Mareanie",
  "Toxapex",
  "Bounsweet",
  "Steenee",
  "Tsareena",
  "Oranguru",
  "Jangmo-o",
  "Hakamo-o",
  "Kommo-o",
  "Tapu Lele",

  // Gen 8
  "Toxel",
  "Toxtricity",
  "Amped Toxtricity",
  "Low Key Toxtricity",
  "Hatenna",
  "Hattrem",
  "Hatterene",
  "Eiscue",
  "Ice Face Eiscue",
  "Noice Face Eiscue",
  "Hisuian Sneasel",
  "Sneasler",
  "Regidrago",

  // Gen 9
  "Lechonk",
  "Oinkologne",
  "Male Oinkologne",
  "Female Oinkologne",
  "Tarountula",
  "Spidops",
  "Pawmi",
  "Pawmo",
  "Pawmot",
  "Toedscool",
  "Toedscruel",
  "Orthworm",
  "Flamigo",
  "Scream Tail",
];

export const PINK_SWITCH_OPTIONAL_SPECIES = [
  // Gen 1
  "Clefairy",
  "Clefable",
  "Jigglypuff",
  "Wigglytuff",

  // Gen 2
  "Cleffa",
  "Igglybuff",
  "Qwilfish",

  // Gen 3
  "Skitty",
  "Delcatty",

  // Gen 4
  "Burmy Trash Cloak",
  "Trash Cloak Burmy",
  "Wormadam Trash Cloak",
  "Trash Cloak Wormadam",
  "Happiny",
  "Blissey",
  "Mime Jr.",
  "Cherrim Sunshine",
  "Sunshine Cherrim",
  "Mesprit",

  // Gen 5
  "Gothita",
  "Gothorita",
  "Gothitelle",
  "Unovan Lilligant",
  "Spring Deerling",
  "Spring Sawsbuck",

  // Gen 6
  "Other Furfrou Trims",

  // Gen 7
  "Salandit",
  "Salazzle",

  // Gen 8
  "Gossifleur",
  "Skwovet",
  "Greedent",
  "Yamper",
  "Boltund",
  "Sinistea",
  "Polteageist",

  // Gen 9
  "Fuecoco",
  "Crocalor",
  "Skeledirge",
  "Tinkatink",
  "Tinkatuff",
  "Tinkaton",
  "Iron Jugulis",
  "Iron Valiant",
];

export const PINK_FRLG_SPECIES = [
  // Starter / Kanto story hunts
  "Charmander",
  "Charizard",
  "Nidoran♀",
  "Nidoran Female",
  "Nidorina",
  "Nidoqueen",
  "Nidoran♂",
  "Nidoran Male",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Jigglypuff",
  "Wigglytuff",
  "Vulpix",
  "Ninetales",
  "Zubat",
  "Golbat",
  "Crobat",
  "Gastly",
  "Haunter",
  "Gengar",
  "Drowzee",
  "Hypno",
  "Grimer",
  "Muk",
  "Koffing",
  "Weezing",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magmar",
  "Lapras",
  "Eevee",
  "Vaporeon",
  "Porygon",
  "Porygon2",

  // Fossils / statics / late game
  "Omanyte",
  "Omastar",
  "Aerodactyl",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Chansey",
  "Blissey",
  "Scyther",
  "Scizor",
  "Pinsir",
  "Smoochum",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",

  // Sevii / postgame
  "Sentret",
  "Furret",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Marill",
  "Azumarill",
  "Wooper",
  "Quagsire",
  "Dunsparce",
  "Qwilfish",
  "Heracross",
  "Murkrow",
  "Misdreavus",
  "Wobbuffet",
  "Sneasel",
  "Remoraid",
  "Delibird",
  "Skarmory",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Unown",
];

export default {
  labels: PINK_QUEST_LABELS,
  switch: PINK_SWITCH_SPECIES,
  switchOptional: PINK_SWITCH_OPTIONAL_SPECIES,
  frlg: PINK_FRLG_SPECIES,
};