// content/_scripts/fetchGameCovers.mjs
// Fetches missing portrait cover artwork from SteamGridDB and saves it locally.
//
// Run:
//   npm run fetch:game-covers
//
// Force replacement of already-cached covers:
//   npm run fetch:game-covers -- --refresh

import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { parse } from "csv-parse/sync";

dotenv.config();

const GAMES_CSV_URL = process.env.GAMES_CSV_URL;
const STEAMGRIDDB_API_KEY = process.env.STEAMGRIDDB_API_KEY;

const API_BASE = "https://www.steamgriddb.com/api/v2";
const MANIFEST_PATH = "./content/_data/gameCovers.json";
const COVER_DIR = "./content/assets/imgs/games/covers";
const PUBLIC_COVER_DIR = "/assets/imgs/games/covers";
const REFRESH = process.argv.includes("--refresh");
const REQUEST_DELAY_MS = 125;

function text(value) {
  if (Array.isArray(value)) return String(value[0] ?? "").trim();
  return String(value ?? "").trim();
}

function kebab(value) {
  return text(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .trim();
}

function normaliseTitle(value) {
  return text(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[™®©]/g, "")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function getField(row, names, fallback = "") {
  const lookup = new Map(
    Object.entries(row || {}).map(([key, value]) => [text(key).toLowerCase(), value])
  );

  for (const name of names) {
    const value = lookup.get(text(name).toLowerCase());
    if (value !== undefined && value !== null && text(value) !== "") {
      return text(value);
    }
  }

  return fallback;
}

function getTitle(row) {
  return getField(row, ["Title", "Name", "Game"]);
}

function getPlatform(row) {
  return getField(row, ["Platform", "Console", "System"], "Unknown");
}
function isDlcRow(row) {
  const type = getField(row, ["Type"]).toLowerCase();
  return type.includes("dlc") || type.includes("expansion");
}

function getCoverOverride(row) {
  return getField(row, ["CoverOverride", "ImageOverride", "Image", "Cover"]);
}

function getSteamGridDbId(row) {
  const raw = getField(row, ["SteamGridDBID", "SteamGridDBId", "SGDBID", "SGDBId"]);
  const id = Number(raw);
  return Number.isFinite(id) && id > 0 ? id : null;
}

function identityKey(title, platform) {
  return `${kebab(platform)}--${kebab(title)}`;
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function readManifest() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    return {
      _meta: {
        source: "SteamGridDB",
        note: "Generated by npm run fetch:game-covers. Safe to commit.",
      },
    };
  }

  try {
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
  } catch (error) {
    throw new Error(`Could not read ${MANIFEST_PATH}: ${error.message}`);
  }
}

function writeManifest(manifest) {
  manifest._meta = {
    source: "SteamGridDB",
    generatedAt: new Date().toISOString(),
    note: "Generated by npm run fetch:game-covers. Safe to commit.",
  };

  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  fs.writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
}

async function apiGet(endpoint, params = {}) {
  const url = new URL(`${API_BASE}${endpoint}`);

  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      url.searchParams.set(key, String(value));
    }
  }

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${STEAMGRIDDB_API_KEY}`,
      Accept: "application/json",
    },
  });

  const body = await response.text();
  let json;

  try {
    json = JSON.parse(body);
  } catch {
    throw new Error(`${response.status} ${response.statusText}: non-JSON response`);
  }

  if (!response.ok || json?.success === false) {
    const details = Array.isArray(json?.errors) ? json.errors.join(", ") : response.statusText;
    throw new Error(`${response.status}: ${details}`);
  }

  await wait(REQUEST_DELAY_MS);
  return json?.data ?? [];
}

async function searchGame(title) {
  const results = await apiGet(`/search/autocomplete/${encodeURIComponent(title)}`);
  if (!Array.isArray(results) || !results.length) return null;

  const wanted = normaliseTitle(title);
  return results.find((game) => normaliseTitle(game?.name) === wanted) ?? null;
}

async function getPortraitGrids(gameId) {
  // SteamGridDB's normal portrait cover size is 600x900.
  // 342x482 is kept as a legacy fallback for games with no modern-size grid.
  for (const dimensions of ["600x900", "342x482"]) {
    const grids = await apiGet(`/grids/game/${gameId}`, {
      dimensions,
      types: "static",
      nsfw: "false",
      humor: "false",
    });

    if (Array.isArray(grids) && grids.length) {
      return grids
        .filter((grid) => grid?.url)
        .sort((a, b) => (Number(b.score) || 0) - (Number(a.score) || 0));
    }
  }

  return [];
}

function extensionFrom(contentType, imageUrl) {
  const type = text(contentType).toLowerCase();
  if (type.includes("image/webp")) return ".webp";
  if (type.includes("image/jpeg")) return ".jpg";
  if (type.includes("image/png")) return ".png";

  try {
    const ext = path.extname(new URL(imageUrl).pathname).toLowerCase();
    if ([".jpg", ".jpeg", ".png", ".webp"].includes(ext)) {
      return ext === ".jpeg" ? ".jpg" : ext;
    }
  } catch {}

  return ".jpg";
}

async function downloadCover(imageUrl, baseFilename) {
  const response = await fetch(imageUrl);
  if (!response.ok) {
    throw new Error(`Image download failed: ${response.status} ${response.statusText}`);
  }

  const extension = extensionFrom(response.headers.get("content-type") || "", imageUrl);
  const filename = `${baseFilename}${extension}`;
  const diskPath = path.join(COVER_DIR, filename);

  fs.mkdirSync(COVER_DIR, { recursive: true });
  fs.writeFileSync(diskPath, Buffer.from(await response.arrayBuffer()));

  return {
    diskPath,
    publicPath: `${PUBLIC_COVER_DIR}/${filename}`,
  };
}

function removeOldCover(entry) {
  if (!entry?.image?.startsWith(`${PUBLIC_COVER_DIR}/`)) return;

  const filename = entry.image.slice(`${PUBLIC_COVER_DIR}/`.length);
  const diskPath = path.join(COVER_DIR, filename);
  if (fs.existsSync(diskPath)) fs.unlinkSync(diskPath);
}

async function main() {
  if (!GAMES_CSV_URL) {
    throw new Error("Missing GAMES_CSV_URL in .env");
  }

  if (!STEAMGRIDDB_API_KEY) {
    throw new Error(
      "Missing STEAMGRIDDB_API_KEY in .env. Generate a key in SteamGridDB preferences first."
    );
  }

  console.log("🎮 Reading the published Games sheet...");

  const response = await fetch(GAMES_CSV_URL);
  if (!response.ok) {
    throw new Error(`Could not fetch games sheet: ${response.status} ${response.statusText}`);
  }

  const rows = parse(await response.text(), {
    columns: true,
    skip_empty_lines: true,
    bom: true,
    relax_column_count: true,
    trim: true,
  }).filter((row) => getTitle(row) && !isDlcRow(row));

  const games = new Map();

  for (const row of rows) {
    const title = getTitle(row);
    const platform = getPlatform(row);
    const key = identityKey(title, platform);

    if (!games.has(key)) {
      games.set(key, {
        key,
        title,
        platform,
        coverOverride: getCoverOverride(row),
        steamGridDbId: getSteamGridDbId(row),
      });
      continue;
    }

    const game = games.get(key);
    if (!game.coverOverride) game.coverOverride = getCoverOverride(row);
    if (!game.steamGridDbId) game.steamGridDbId = getSteamGridDbId(row);
  }

  const manifest = readManifest();
  let fetched = 0;
  let skipped = 0;
  let unresolved = 0;
  let failed = 0;

  for (const game of games.values()) {
    if (game.coverOverride) {
      console.log(`↪ ${game.title} (${game.platform}) — CoverOverride set`);
      skipped++;
      continue;
    }

    const existing = manifest[game.key];
    const existingDiskFile = existing?.image?.startsWith(`${PUBLIC_COVER_DIR}/`)
      ? path.join(COVER_DIR, existing.image.slice(`${PUBLIC_COVER_DIR}/`.length))
      : null;

    if (!REFRESH && existing?.image && existingDiskFile && fs.existsSync(existingDiskFile)) {
      console.log(`✓ ${game.title} (${game.platform}) — already cached`);
      skipped++;
      continue;
    }

    try {
      const sgdbGame = game.steamGridDbId
        ? { id: game.steamGridDbId, name: game.title, forced: true }
        : await searchGame(game.title);

      if (!sgdbGame?.id) {
        console.warn(
          `? ${game.title} (${game.platform}) — no exact SteamGridDB title match. Add SteamGridDBID to the sheet.`
        );
        unresolved++;
        continue;
      }

      const grid = (await getPortraitGrids(sgdbGame.id))[0];
      if (!grid?.url) {
        console.warn(`? ${game.title} (${game.platform}) — no portrait static grid found`);
        unresolved++;
        continue;
      }

      if (REFRESH && existing) removeOldCover(existing);

      const downloaded = await downloadCover(grid.url, game.key);
      manifest[game.key] = {
        title: game.title,
        platform: game.platform,
        steamGridDbId: Number(sgdbGame.id),
        steamGridDbName: sgdbGame.name || game.title,
        gridId: grid.id ?? null,
        width: grid.width ?? null,
        height: grid.height ?? null,
        image: downloaded.publicPath,
        sourceImage: grid.url,
      };

      writeManifest(manifest);
      fetched++;
      console.log(`↓ ${game.title} (${game.platform}) — ${downloaded.publicPath}`);
    } catch (error) {
      failed++;
      console.warn(`! ${game.title} (${game.platform}) — ${error.message}`);
    }
  }

  writeManifest(manifest);

  console.log("");
  console.log(
    `✅ Covers complete: ${fetched} fetched, ${skipped} cached/overridden, ${unresolved} unresolved, ${failed} failed.`
  );

  if (unresolved) {
    console.log("   Add SteamGridDBID for unresolved titles, then run the command again.");
  }
}

main().catch((error) => {
  console.error(`❌ ${error.message}`);
  process.exitCode = 1;
});
