// content/_scripts/fetchGameCovers.mjs
// Fetches missing portrait cover artwork from SteamGridDB and saves it locally.
//
// Sources:
//   Playnite export = tracked/library games
//   Physical sheet   = optional physical-only games
//
// Run:
//   npm run fetch:game-covers
//
// Force replacement of already-cached covers:
//   npm run fetch:game-covers -- --refresh

import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { parse } from "csv-parse/sync";

dotenv.config();

const PLAYNITE_LIBRARY_PATH = path.resolve(
  process.env.PLAYNITE_LIBRARY_PATH || "./content/_data/playnite-library.json"
);
const PHYSICAL_GAMES_CSV_URL = process.env.PHYSICAL_GAMES_CSV_URL || "";
const STEAMGRIDDB_API_KEY = process.env.STEAMGRIDDB_API_KEY;

const API_BASE = "https://www.steamgriddb.com/api/v2";
const MANIFEST_PATH = "./content/_data/gameCovers.json";
const COVER_DIR = "./content/assets/imgs/games/covers";
const PUBLIC_COVER_DIR = "/assets/imgs/games/covers";
const REFRESH = process.argv.includes("--refresh");
const REQUEST_DELAY_MS = 125;

function text(value) {
  return String(value ?? "").trim();
}

function kebab(value) {
  return text(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function normaliseTitle(value) {
  return text(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[™®©]/g, "")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function normalisePlatform(name) {
  const raw = text(name).toLowerCase();
  const aliases = new Map([
    ["pc (windows)", "Windows PC"],
    ["sony playstation 5", "PlayStation 5"],
    ["sony playstation 4", "PlayStation 4"],
    ["sony playstation 3", "PlayStation 3"],
    ["sony playstation vita", "PlayStation Vita"],
    ["nintendo switch", "Nintendo Switch"],
    ["nintendo switch 2", "Nintendo Switch 2"],
    ["nintendo 3ds", "Nintendo 3DS"],
    ["nintendo ds", "Nintendo DS"],
    ["nintendo gamecube", "Nintendo GameCube"],
    ["game boy", "Game Boy"],
    ["game boy advance", "Game Boy Advance"],
    ["wii", "Wii"],
    ["wii u", "Wii U"],
  ]);

  return aliases.get(raw) || text(name) || "Unknown";
}

function identityKey(title, platform) {
  return `${kebab(platform)}--${kebab(title)}`;
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function readManifest() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    return {
      _meta: {
        source: "SteamGridDB",
        note: "Generated by npm run fetch:game-covers. Safe to commit.",
      },
    };
  }

  try {
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
  } catch (error) {
    throw new Error(`Could not read ${MANIFEST_PATH}: ${error.message}`);
  }
}

function writeManifest(manifest) {
  manifest._meta = {
    source: "SteamGridDB",
    generatedAt: new Date().toISOString(),
    note: "Generated from Playnite + physical collection by npm run fetch:game-covers.",
  };

  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  fs.writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
}

async function apiGet(endpoint, params = {}) {
  const url = new URL(`${API_BASE}${endpoint}`);

  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      url.searchParams.set(key, String(value));
    }
  }

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${STEAMGRIDDB_API_KEY}`,
      Accept: "application/json",
    },
  });

  const body = await response.text();
  let json;

  try {
    json = JSON.parse(body);
  } catch {
    throw new Error(`${response.status} ${response.statusText}: non-JSON response`);
  }

  if (!response.ok || json?.success === false) {
    const details = Array.isArray(json?.errors)
      ? json.errors.join(", ")
      : response.statusText;
    throw new Error(`${response.status}: ${details}`);
  }

  await wait(REQUEST_DELAY_MS);
  return json?.data ?? [];
}

async function gameFromSteamAppId(appId) {
  if (!appId) return null;

  try {
    const result = await apiGet(`/games/steam/${encodeURIComponent(appId)}`);
    if (Array.isArray(result)) return result[0] || null;
    return result?.id ? result : null;
  } catch {
    return null;
  }
}

async function searchGame(title) {
  const results = await apiGet(`/search/autocomplete/${encodeURIComponent(title)}`);
  if (!Array.isArray(results) || !results.length) return null;

  const wanted = normaliseTitle(title);
  return results.find((game) => normaliseTitle(game?.name) === wanted) ?? null;
}

async function resolveSgdbGame(game) {
  if (game.steamAppId) {
    const steamMatch = await gameFromSteamAppId(game.steamAppId);
    if (steamMatch?.id) return steamMatch;
  }

  return searchGame(game.title);
}

async function getPortraitGrids(gameId) {
  for (const dimensions of ["600x900", "342x482"]) {
    const grids = await apiGet(`/grids/game/${gameId}`, {
      dimensions,
      types: "static",
      nsfw: "false",
      humor: "false",
    });

    if (Array.isArray(grids) && grids.length) {
      return grids
        .filter((grid) => grid?.url)
        .sort((a, b) => (Number(b.score) || 0) - (Number(a.score) || 0));
    }
  }

  return [];
}

function extensionFrom(contentType, imageUrl) {
  const type = text(contentType).toLowerCase();
  if (type.includes("image/webp")) return ".webp";
  if (type.includes("image/jpeg")) return ".jpg";
  if (type.includes("image/png")) return ".png";

  try {
    const ext = path.extname(new URL(imageUrl).pathname).toLowerCase();
    if ([".jpg", ".jpeg", ".png", ".webp"].includes(ext)) {
      return ext === ".jpeg" ? ".jpg" : ext;
    }
  } catch {}

  return ".jpg";
}

async function downloadCover(imageUrl, baseFilename) {
  const response = await fetch(imageUrl);
  if (!response.ok) {
    throw new Error(`Image download failed: ${response.status} ${response.statusText}`);
  }

  const extension = extensionFrom(
    response.headers.get("content-type") || "",
    imageUrl
  );
  const filename = `${baseFilename}${extension}`;
  const diskPath = path.join(COVER_DIR, filename);

  fs.mkdirSync(COVER_DIR, { recursive: true });
  fs.writeFileSync(diskPath, Buffer.from(await response.arrayBuffer()));

  return {
    diskPath,
    publicPath: `${PUBLIC_COVER_DIR}/${filename}`,
  };
}

function removeOldCover(entry) {
  if (!entry?.image?.startsWith(`${PUBLIC_COVER_DIR}/`)) return;

  const filename = entry.image.slice(`${PUBLIC_COVER_DIR}/`.length);
  const diskPath = path.join(COVER_DIR, filename);
  if (fs.existsSync(diskPath)) fs.unlinkSync(diskPath);
}

function addGame(games, game) {
  if (!game.title || !game.platform) return;
  const key = identityKey(game.title, game.platform);

  if (!games.has(key)) {
    games.set(key, { ...game, key });
    return;
  }

  const existing = games.get(key);
  if (!existing.steamAppId && game.steamAppId) {
    existing.steamAppId = game.steamAppId;
  }
  if (!existing.coverOverride && game.coverOverride) {
    existing.coverOverride = game.coverOverride;
  }
}

function loadPlayniteGames(games) {
  if (!fs.existsSync(PLAYNITE_LIBRARY_PATH)) {
    throw new Error(`Missing Playnite export: ${PLAYNITE_LIBRARY_PATH}`);
  }

  const raw = JSON.parse(fs.readFileSync(PLAYNITE_LIBRARY_PATH, "utf8"));
  const rows = Array.isArray(raw?.games) ? raw.games : [];

  for (const row of rows) {
    if (row.hidden || !text(row.name)) continue;

    const platforms = Array.isArray(row.platforms) && row.platforms.length
      ? row.platforms
      : ["Unknown"];

    for (const platform of platforms) {
      addGame(games, {
        title: text(row.name),
        platform: normalisePlatform(platform),
        steamAppId: Number(row.steamAppId) || null,
        coverOverride: "",
        source: "playnite",
      });
    }
  }
}

async function loadPhysicalGames(games) {
  if (!PHYSICAL_GAMES_CSV_URL) return;

  const response = await fetch(PHYSICAL_GAMES_CSV_URL);
  if (!response.ok) {
    throw new Error(
      `Could not fetch physical games sheet: ${response.status} ${response.statusText}`
    );
  }

  const rows = parse(await response.text(), {
    columns: true,
    skip_empty_lines: true,
    bom: true,
    relax_column_count: true,
    trim: true,
  });

  for (const row of rows) {
    const title = text(row.Title);
    const platform = normalisePlatform(row.Platform);
    if (!title || !text(row.Platform)) continue;

    addGame(games, {
      title,
      platform,
      steamAppId: null,
      coverOverride: text(row.CoverOverride),
      source: "physical",
    });
  }
}

async function main() {
  if (!STEAMGRIDDB_API_KEY) {
    throw new Error(
      "Missing STEAMGRIDDB_API_KEY in .env. Generate a key in SteamGridDB preferences first."
    );
  }

  console.log("🎮 Reading Playnite library...");

  const games = new Map();
  loadPlayniteGames(games);
  await loadPhysicalGames(games);

  console.log(`🎮 Found ${games.size} platform-specific game entries.`);

  const manifest = readManifest();
  let fetched = 0;
  let skipped = 0;
  let unresolved = 0;
  let failed = 0;

  for (const game of games.values()) {
    if (game.coverOverride) {
      console.log(`↪ ${game.title} (${game.platform}) — CoverOverride set`);
      skipped++;
      continue;
    }

    const existing = manifest[game.key];
    const existingDiskFile = existing?.image?.startsWith(`${PUBLIC_COVER_DIR}/`)
      ? path.join(COVER_DIR, existing.image.slice(`${PUBLIC_COVER_DIR}/`.length))
      : null;

    if (
      !REFRESH &&
      existing?.image &&
      existingDiskFile &&
      fs.existsSync(existingDiskFile)
    ) {
      console.log(`✓ ${game.title} (${game.platform}) — already cached`);
      skipped++;
      continue;
    }

    try {
      const sgdbGame = await resolveSgdbGame(game);

      if (!sgdbGame?.id) {
        console.warn(
          `? ${game.title} (${game.platform}) — no exact SteamGridDB match`
        );
        unresolved++;
        continue;
      }

      const grid = (await getPortraitGrids(sgdbGame.id))[0];
      if (!grid?.url) {
        console.warn(
          `? ${game.title} (${game.platform}) — no portrait static grid found`
        );
        unresolved++;
        continue;
      }

      if (REFRESH && existing) removeOldCover(existing);

      const downloaded = await downloadCover(grid.url, game.key);
      manifest[game.key] = {
        title: game.title,
        platform: game.platform,
        steamGridDbId: Number(sgdbGame.id),
        steamGridDbName: sgdbGame.name || game.title,
        steamAppId: game.steamAppId || null,
        gridId: grid.id ?? null,
        width: grid.width ?? null,
        height: grid.height ?? null,
        image: downloaded.publicPath,
        sourceImage: grid.url,
      };

      writeManifest(manifest);
      fetched++;
      console.log(`↓ ${game.title} (${game.platform}) — ${downloaded.publicPath}`);
    } catch (error) {
      failed++;
      console.warn(`! ${game.title} (${game.platform}) — ${error.message}`);
    }
  }

  writeManifest(manifest);

  console.log("");
  console.log(
    `✅ Covers complete: ${fetched} fetched, ${skipped} cached/overridden, ` +
    `${unresolved} unresolved, ${failed} failed.`
  );
}

main().catch((error) => {
  console.error(`❌ ${error.message}`);
  process.exitCode = 1;
});
